# Generated by Django 5.1.1 on 2024-09-10 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(blank=True, max_length=50, null=True)),
                ('attributes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='BATTLE_INPROGRESS', max_length=50)),
                ('result', models.JSONField(blank=True, null=True)),
                ('pokemon_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_a', to='pokemon.pokemon')),
                ('pokemon_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_b', to='pokemon.pokemon')),
            ],
        ),
    ]
