# Generated by Django 5.1.1 on 2024-09-11 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_managers_alter_battle_pokemon_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='pokemon_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_b', to='pokemon.pokemon'),
        ),
    ]
